server:
  port: 8000
  servlet:
    context-path: /api
spring:
  config:
    import: secret.yml
  liquibase:
    change-log: db/changelog.yaml
app:
  nfs:
    path: /home/quicklybly/IdeaProjects/kinder/media/images
